filename: "Dataset/LI-Medium_Trans.csv"
delimiter: ','
columns:
    - Timestamp
    - From Bank
    - Account
    - To Bank
    - Account.1
    - Amount Received
    - Receiving Currency
    - Amount Paid
    - Payment Currency
    - Payment Format
    - Is Laundering